<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><UseWPF>true</UseWPF></PropertyGroup>
  <ItemGroup><PackageReference Include="Interop.UIAutomationClient" Version="10.19041.0" /></ItemGroup>
  <ItemGroup><PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" /></ItemGroup>
</Project>
