<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>DeAI</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>deai.ico</ApplicationIcon>
    <Version>0.1.0</Version>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../DeAI.Core/DeAI.Core.csproj" /><EmbeddedResource Include="deai.ico" LogicalName="DeAI.ico" /></ItemGroup>
</Project>
